//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PvI_KP_Entities : DbContext
    {
        public PvI_KP_Entities()
            : base("name=PvI_KP_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Shared> Shared { get; set; }
        public virtual DbSet<UserGroups> UserGroups { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<RemovedFiles> RemovedFiles { get; set; }
        public virtual DbSet<FileServers> FileServers { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<Repositories> Repositories { get; set; }
        public virtual DbSet<SharedLink> SharedLink { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
