//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repositories
    {
        public int id { get; set; }
        public string location { get; set; }
        public Nullable<bool> archived { get; set; }
        public Nullable<bool> @protected { get; set; }
        public string user_name { get; set; }
    }
}
