//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shared
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string path { get; set; }
        public string type { get; set; }
        public string target_type { get; set; }
        public string target_name { get; set; }
        public Nullable<int> link_number { get; set; }
        public string link_url { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
